//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hovis.Web.Base.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Application_Standard_Settings
    {
        public int ID { get; set; }
        public string Setting { get; set; }
        public string SettingValue { get; set; }
    }
}
