//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hovis.Web.Base.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Employee_Department
    {
        public t_Employee_Department()
        {
            this.t_New_Starter_Details = new HashSet<t_New_Starter_Details>();
        }
    
        public int DeptID { get; set; }
        public string DeptDescription { get; set; }
    
        public virtual ICollection<t_New_Starter_Details> t_New_Starter_Details { get; set; }
    }
}
