//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hovis.Web.Base.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Employee_Location
    {
        public t_Employee_Location()
        {
            this.t_New_Starter_Details = new HashSet<t_New_Starter_Details>();
            this.t_New_Starter_Details1 = new HashSet<t_New_Starter_Details>();
            this.t_Servicedesk_Contact = new HashSet<t_Servicedesk_Contact>();
            this.t_Leaver_Details = new HashSet<t_Leaver_Details>();
        }
    
        public int LocID { get; set; }
        public string LocationDescription { get; set; }
    
        public virtual ICollection<t_New_Starter_Details> t_New_Starter_Details { get; set; }
        public virtual ICollection<t_New_Starter_Details> t_New_Starter_Details1 { get; set; }
        public virtual ICollection<t_Servicedesk_Contact> t_Servicedesk_Contact { get; set; }
        public virtual ICollection<t_Leaver_Details> t_Leaver_Details { get; set; }
    }
}
