//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hovis.Web.Base.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Leaver_Details
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> DateFirstRequested { get; set; }
        public string RequestorsName { get; set; }
        public string RequestorsTelephoneNumber { get; set; }
        public int RequestorsLocation { get; set; }
        public string LeaversName { get; set; }
        public string DeleteConfirmed { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    
        public virtual t_Employee_Location t_Employee_Location { get; set; }
    }
}
