//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hovis.Web.Base.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_New_Starter_Details
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> DateFirstRequested { get; set; }
        public string RequestorsName { get; set; }
        public string RaisedBy { get; set; }
        public string RequestorsTelephoneNumber { get; set; }
        public int RequestorsLocation { get; set; }
        public string NewStartersName { get; set; }
        public string NewStartersRole { get; set; }
        public int EmploymentType { get; set; }
        public int NewStarterDept { get; set; }
        public int NewStarterLocation { get; set; }
        public Nullable<System.DateTime> NewStarterDate { get; set; }
        public string ManagersName { get; set; }
        public string DeptCostCentre { get; set; }
        public string GmailRequired { get; set; }
        public string LaptopRequired { get; set; }
        public string MobileRequired { get; set; }
        public string RemoteAccessVPN { get; set; }
        public string CreationConfirmed { get; set; }
        public string CreationConfirmedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual t_Employee_Department t_Employee_Department { get; set; }
        public virtual t_Employment_Type t_Employment_Type { get; set; }
        public virtual t_Employee_Location t_Employee_Location { get; set; }
        public virtual t_Employee_Location t_Employee_Location1 { get; set; }
    }
}
