//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hovis.Web.Base.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_AD_Users_Lookup
    {
        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string jobTitle { get; set; }
        public string telephonenumber { get; set; }
        public string email { get; set; }
        public string mobileNumber { get; set; }
        public string physicaldeliveryoffice { get; set; }
        public string department { get; set; }
        public string l { get; set; }
        public string company { get; set; }
        public string distinguishedName { get; set; }
        public string lastlogondate { get; set; }
        public string lastlogontime { get; set; }
        public string lastsync { get; set; }
        public string st { get; set; }
        public string webpage { get; set; }
        public string samaccountname { get; set; }
        public string telNumber { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public string ManagerFirstName { get; set; }
        public string ManagerLastName { get; set; }
        public string ManagerEmail { get; set; }
    }
}
